# ------------------------------------------------------------------
# SIMULATION: ROS2 Multi-Robot MAPF Controller
#
# This ROS 2 node executes task plans generated by MAPF algorithms
# on a simulated warehouse robots.
#
# It is responsible for loading precomputed pickup and delivery paths,
# dispatching trajectories to the navigation stack, coordinating robot
# synchronization, controlling the box lifter mechanism, and publishing
# experiment telemetry for offline analysis and benchmarking, including
# ICBS and RHCR modes. After initialization, the controller waits for 
# localization to stabilize before beginning trajectory execution.
# ------------------------------------------------------------------

import json
from datetime import datetime
import rclpy
from rclpy.node import Node
import dots_devel_interfaces.msg
import os
from .submodules.path_action import PathAction
from std_msgs.msg import String, Bool
from rclpy.duration import Duration

# Global controller parameters shared across all robots
class G:
    mv = 0.2
    w = 3.0
    ekf_wait = 15.0

# Waypoint representation used to build navigation paths
class WP:
    def __init__(self,x,y):
        self.x = x
        self.y = y
        self.th = 0.0
        self.vx = 0.0
        self.vy = 0.0
        self.mvx = G.mv
        self.mvy = G.mv
        self.dwell = 1.0

# ------------------------------------------------------------------
# Loads and parses the path-planning solution assigned to one robot.
#
# The path files are generated offline by a MAPF solver (ICBS or RHCR)
# and contain alternating pickup and delivery trajectories.
#
# During loading, grid coordinates are converted into Gazebo world
# coordinates so the resulting waypoints can be sent directly to the
# navigation stack.
# ------------------------------------------------------------------    

class Controller(Node):

    # ------------------------------------------------------------------
    # Controller initialization
    #
    # The initialization phase sets up the entire execution context for
    # a single robot participating in a MAPF experiment. Startup consists
    # of five major stages:
    #
    # 1. Resolve robot identity and assign a unique internal ID
    # 2. Configure experiment and MAPF execution parameters
    # 3. Load and preprocess trajectory data for task execution
    # 4. Initialize ROS communication interfaces and timers
    # 5. Prepare runtime state and experiment tracking structures
    # ------------------------------------------------------------------

    def __init__(self):
        super().__init__('controller')

        # Extract robot namespace and convert it into a zero-based robot index
        self.robot_name = self.get_namespace()[1:]
        self.robot_id = int(self.robot_name.split("_")[-1]) - 1

        self.action = PathAction(self)

        self.period = 0.05
        
        # Periodic control loop driving the execution state machine
        self.timer = self.create_timer(self.period,self.control_loop_callback)

        self.total_robots = 3

        # Select which MAPF solution will be executed
        # EDIT HERE: Mode ("ICBS" or"RHCR")
        self.mode = "ICBS"

        # EDIT HERE: Box quantity (8-10 boxes)
        self.box_quantity = 8

        # EDIT HERE: Example (Example 1-14)
        self.example = 14

        # Generated trajectories produced by each MAPF solver
        self.paths_files = {
            "ICBS":f"instances/{self.box_quantity}_boxes/example{self.example}/example{self.example}_icbs_converted_paths.txt", 
            "RHCR":f"instances/{self.box_quantity}_boxes/example{self.example}/example{self.example}_rhcr_converted_paths.txt",
        }

        self.tasks = self.load_tasks_from_file()
        
        # Tracks which pickup-delivery task pair is currently active
        self.current_task_index = 0

        # Current execution stage of the robot workflow
        self.stage = "pickup"
        self.path = []

        self.started = False
        self.finished = False

        # Allow localization to stabilize before starting navigation
        self.delay_loops = int(G.ekf_wait / self.period)

        # Stores robots that have completed the current synchronization barrier
        self.pickup_finished = set()
        self.delivery_finished = set()

        # ROS2 topic used for robot synchronization
        self.sync_pub = self.create_publisher(String,"/robots_sync",10)

        self.sync_sub = self.create_subscription(
            String,
            "/robots_sync",
            self.sync_callback,
            10
        )

        self.delay_start_time = None

        self.lifter_pub = self.create_publisher(Bool, 'lifter', 10)
        
        # Prevents repeated lift commands during the same operation
        self.lift_cmd_sent = False

        # ROSbag experiment topics recorded for experiment analysis
        self.experiment_metadata_pub = self.create_publisher(String,"/experiment_metadata",10)
        self.tasks_pub = self.create_publisher(String,"/tasks",10)
        self.task_events_pub = self.create_publisher(String,"/task_events",10)
        self.next_waypoint_pub = self.create_publisher(String,f"/{self.robot_name}/next_waypoint",10)
        self.robot_state_pub = self.create_publisher(String,f"/{self.robot_name}/robot_state",10)
        self.planned_path_pub = self.create_publisher(String,f"/{self.robot_name}/planned_path",10)

        self.publish_experiment_metadata()
        self.publish_tasks()

    # ------------------------------------------------------------------
    # Loads and parses the path-planning solution assigned to this robot.
    #
    # The path files are generated offline by a MAPF solver (ICBS or RHCR)
    # and contain alternating pickup and delivery trajectories.
    #
    # During loading, grid coordinates are converted into Gazebo world
    # coordinates so the resulting waypoints can be sent directly to the
    # navigation stack.
    # ------------------------------------------------------------------

    def load_tasks_from_file(self):
        file_path = os.path.join(os.path.dirname(__file__),self.paths_files[self.mode])

        if not os.path.exists(file_path):
            self.get_logger().error("Path file not found!!")
            return []
        
        self.get_logger().info(f"Chosen algorithm: {self.mode}")

        with open(file_path,"r") as f:
            lines = [l.strip() for l in f.readlines() if l.strip()]

        robots = []
        i = 0

        while i < len(lines):
            robot_id = int(lines[i])
            i += 1
            tasks = []

            while i < len(lines) and not lines[i].isdigit():
                coords = list(map(float,lines[i].split()))
                path = []
                for j in range(0,len(coords),2):
                    # Convert grid coordinates from the MAPF solution into Gazebo coordinates
                    
                    # GRID 8 columns
                    # x = coords[j+1] * (3.7/8) - 1.85
                    # y = 1.85 - coords[j] * (3.7/8)

                    # GRID 6 columns, 3.7m x 3.7m
                    x = coords[j+1] * (3.7/6) - 1.85
                    y = 1.85 - coords[j] * (3.7/6)
                    
                    self.get_logger().info(
                        f"{self.robot_name} loaded waypoint ({x:.2f}, {y:.2f})"
                    )
                    path.append(WP(x,y))

                tasks.append(path)
                i += 1

            paired = []
            for j in range(0,len(tasks),2):
                pickup = tasks[j]
                delivery = tasks[j+1] if j+1 < len(tasks) else []
                
                # MAPF output alternates pickup and delivery trajectories
                paired.append((pickup,delivery))
                
            robots.append(paired)

        # Only returns tasks from this robot
        return robots[self.robot_id]

    def get_current_paths(self):
        if self.current_task_index >= len(self.tasks):
            return None, None

        # Returns the pickup and delivery paths for the active task
        return self.tasks[self.current_task_index]
    
    # ------------------------------------------------------------------
    # Converts the current waypoint sequence into a DotsPath message and
    # dispatches it to the path-following action server.
    #
    # This function acts as the bridge between the high-level task planner
    # and the low-level navigation controller responsible for executing
    # the trajectory.
    # ------------------------------------------------------------------

    def send_full_path(self):
        msg = dots_devel_interfaces.msg.DotsPath()
        msg.frame_id = "map"

        # Build a navigation message from the current waypoint sequence
        for p in self.path:

            wp = dots_devel_interfaces.msg.DotsWaypoint()

            wp.position.x = p.x
            wp.position.y = p.y
            wp.position.th = p.th

            wp.velocity.x = p.vx
            wp.velocity.y = p.vy
            wp.velocity.w = 0.0

            wp.max_velocity.x = p.mvx
            wp.max_velocity.y = p.mvy
            wp.max_velocity.w = G.w

            msg.path.append(wp)

        self.get_logger().info(f"Sending path ({len(msg.path)} waypoints)")
        
        self.action.send_goal(msg)
        self.started = True

    # ------------------------------------------------------------------
    # Receives synchronization messages from other robots.
    #
    # In ICBS mode, robots must wait for all teammates to complete the
    # current pickup or delivery stage before advancing. The received
    # messages are stored locally and later evaluated by the control loop.
    # ------------------------------------------------------------------

    def sync_callback(self,msg):
        stage, robot = msg.data.split(":")

        if stage == "pickup":
            self.pickup_finished.add(robot)

        if stage == "delivery":
            self.delivery_finished.add(robot)
            
    # ------------------------------------------------------------------
    # Main execution state machine.
    #
    # This callback coordinates the entire robot workflow:
    #   1. Wait for localization initialization
    #   2. Execute pickup navigation
    #   3. Simulate box collection
    #   4. Execute delivery navigation
    #   5. Simulate box release
    #   6. Advance to the next task
    #
    # The exact behavior depends on the selected planning strategy:
    #   - RHCR: robots operate independently
    #   - ICBS: robots synchronize at pickup and delivery waypoints
    # ------------------------------------------------------------------

    def control_loop_callback(self):
        if self.finished:
            return

        # EKF delay to allow localization to stabilize before starting navigation
        if self.delay_loops > 0:
            if self.delay_loops % 10 == 0:
                self.get_logger().info("Waiting for EKF...")

            self.delay_loops -= 1

            if self.delay_loops == 0:
                lift_msg = Bool()
                lift_msg.data = False
                self.lifter_pub.publish(lift_msg)
                self.get_logger().info("Lift initialized DOWN")

            return

        if not self.started:
            pickup, delivery = self.get_current_paths()

            if pickup is None:
                if self.mode == "ICBS":
                    self.get_logger().info("All tasks finished, signaling done to peers!")
                    
                    # Avoids re-entering this block every iteration
                    self.started = True
                    self.stage = "done_republishing"
                else:
                    self.get_logger().info("All tasks finished!")
                    self.finished = True

                self.publish_task_event("finished")
                self.publish_robot_state("finished")
                return

            self.path = pickup if self.stage == "pickup" else delivery
            self.send_full_path()
            return

        if self.action.busy:
            return

        # RHCR executes tasks independently without global synchronization
        if self.mode == "RHCR":
            if self.stage == "pickup":
                self.publish_planned_path()
                self.publish_next_waypoint()

                self.publish_robot_state("navigating_to_pickup")
                self.publish_task_event("pickup_started")

                self.delay_start_time = self.get_clock().now()
                self.lift_cmd_sent = False
                self.stage = "pickup_delay"

                return

            if self.stage == "pickup_delay":

                self.publish_robot_state("collecting_box")

                if self.get_clock().now() - self.delay_start_time > Duration(seconds=2):
                    if not self.lift_cmd_sent:
                        lift_msg = Bool()
                        lift_msg.data = True
                        self.lifter_pub.publish(lift_msg)
                        self.lift_cmd_sent = True
                        self.get_logger().info("Lift UP at pickup waypoint")

                    if self.get_clock().now() - self.delay_start_time > Duration(seconds=4):

                        self.publish_task_event("pickup_finished")
                        self.stage = "delivery"
                        self.started = False

                return

            if self.stage == "delivery":
                self.publish_planned_path()
                self.publish_next_waypoint()

                self.publish_robot_state("navigating_to_delivery")
                self.publish_task_event("delivery_started")

                self.delay_start_time = self.get_clock().now()
                self.lift_cmd_sent = False
                self.stage = "delivery_delay"

                return

            if self.stage == "delivery_delay":
                self.publish_robot_state("delivering_box")

                if self.get_clock().now() - self.delay_start_time > Duration(seconds=2):
                    if not self.lift_cmd_sent:
                        lift_msg = Bool()
                        lift_msg.data = False
                        self.lifter_pub.publish(lift_msg)
                        self.lift_cmd_sent = True
                        self.get_logger().info("Lift DOWN at delivery waypoint")
                        self.delay_start_time = self.get_clock().now()
                        self.stage = "post_delivery_wait"

                return

            if self.stage == "post_delivery_wait":
                if self.get_clock().now() - self.delay_start_time > Duration(seconds=2):
                    self.publish_task_event("delivery_finished")
                    self.current_task_index += 1
                    self.stage = "pickup"
                    self.started = False

                return


        # ICBS introduces synchronization barriers between task phases
        if self.mode == "ICBS":
            if self.stage == "done_republishing":
                msg = String()
                msg.data = f"pickup:{self.robot_name}"
                
                # Re-broadcast status messages to handle late-joining robots
                self.sync_pub.publish(msg)
                msg.data = f"delivery:{self.robot_name}"
                self.sync_pub.publish(msg)

                self.publish_robot_state("finished")

                return

            if self.stage == "pickup":
                self.publish_planned_path()
                self.publish_next_waypoint()

                self.publish_robot_state("navigating_to_pickup")
                self.publish_task_event("pickup_started")

                msg = String()
                msg.data = f"pickup:{self.robot_name}"
                self.sync_pub.publish(msg)

                self.stage = "waiting_all_pickups"

                return

            if self.stage == "waiting_all_pickups":

                self.publish_task_event("waiting_sync")

                # The republic continues so that robots that arrived later do not 
                # miss the message
                msg = String()
                msg.data = f"pickup:{self.robot_name}"
                self.sync_pub.publish(msg)

                if (len(self.pickup_finished) != self.total_robots):
                    self.publish_robot_state("navigating_to_pickup")

                if len(self.pickup_finished) == self.total_robots:

                    self.delay_start_time = self.get_clock().now()
                    self.lift_cmd_sent = False
                    self.stage = "pickup_delay"

                return

            if self.stage == "pickup_delay":
                self.publish_robot_state("collecting_box")
                elapsed = self.get_clock().now() - self.delay_start_time

                # Simulate the time required to collect a box from storage
                if not self.lift_cmd_sent and elapsed > Duration(seconds=1):
                    lift_msg = Bool()
                    lift_msg.data = True
                    self.lifter_pub.publish(lift_msg)
                    self.lift_cmd_sent = True
                    self.get_logger().info("Lift UP at pickup waypoint")

                if elapsed > Duration(seconds=3):
                    self.publish_robot_state("navigating_to_delivery")
                    self.publish_task_event("pickup_finished")

                    self.stage = "delivery"
                    self.started = False
                    self.pickup_finished.clear()

                return

            if self.stage == "delivery":
                self.publish_robot_state("navigating_to_delivery")
                self.publish_task_event("delivery_started")

                self.publish_planned_path()
                self.publish_next_waypoint()

                msg = String()
                msg.data = f"delivery:{self.robot_name}"
                self.sync_pub.publish(msg)

                self.stage = "waiting_all_deliveries"

                return

            if self.stage == "waiting_all_deliveries":
                self.publish_task_event("waiting_sync")

                # The republic continues so that robots that arrived later do not 
                # miss the message
                msg = String()
                msg.data = f"delivery:{self.robot_name}"
                self.sync_pub.publish(msg)

                if (len(self.delivery_finished) != self.total_robots):
                    self.publish_robot_state("navigating_to_delivery")

                if len(self.delivery_finished) == self.total_robots:

                    self.delay_start_time = self.get_clock().now()
                    self.lift_cmd_sent = False
                    self.stage = "delivery_delay"

                return

            if self.stage == "delivery_delay":
                self.publish_robot_state("delivering_box")

                elapsed = self.get_clock().now() - self.delay_start_time
                
                # Simulate the time required to unload the transported box
                if elapsed > Duration(seconds=1):
                    if not self.lift_cmd_sent:
                        lift_msg = Bool()
                        lift_msg.data = False
                        self.lifter_pub.publish(lift_msg)
                        self.lift_cmd_sent = True
                        self.get_logger().info("Lift DOWN at delivery waypoint")
                        self.delay_start_time = self.get_clock().now()
                        self.stage = "post_delivery_wait"

                return

            if self.stage == "post_delivery_wait":
                if self.get_clock().now() - self.delay_start_time > Duration(seconds=1):
                    self.publish_task_event("delivery_finished")
                    self.delivery_finished.clear()
                    self.current_task_index += 1
                    self.stage = "pickup"
                    self.started = False

                return

    # ------------------------------------------------------------------
    # Publishes experiment-level metadata used for analysis.
    #
    # This information is recorded in rosbags and allows experiments to
    # be identified later by scenario, algorithm, robot count, and other
    # configuration parameters.
    # ------------------------------------------------------------------

    def publish_experiment_metadata(self):
        metadata = {
            "timestamp": str(datetime.now()),
            "algorithm": self.mode,
            "num_robots": self.total_robots,
            "num_boxes": self.box_quantity,
            "num_example": self.example
        }

        msg = String()
        msg.data = json.dumps(metadata)

        self.experiment_metadata_pub.publish(msg)

    # Publishes a summary of all tasks assigned to this robot
    def publish_tasks(self):
        all_tasks = []

        for idx, (pickup, delivery) in enumerate(self.tasks):
            pickup_goal = pickup[-1]
            delivery_goal = delivery[-1]

            task_data = {
                "robot_id": self.robot_id,
                "task_index": idx,

                "pickup_goal": {
                    "x": pickup_goal.x, 
                    "y": pickup_goal.y
                },

                "delivery_goal": {
                    "x": delivery_goal.x,
                    "y": delivery_goal.y
                }
            }

            all_tasks.append(task_data)

        msg = String()
        msg.data = json.dumps(all_tasks)

        self.tasks_pub.publish(msg)
        
    # Records high-level task execution events
    def publish_task_event(self, event_name):
        data = {
            "timestamp": str(self.get_clock().now().nanoseconds),
            "robot": self.robot_name,
            "event": event_name,
            "task_index": self.current_task_index,
            "stage": self.stage
        }

        msg = String()
        msg.data = json.dumps(data)

        self.task_events_pub.publish(msg)

    # Publishes the current task goal location
    def publish_next_waypoint(self):
        if len(self.path) == 0:
            return
        
        goal = self.path[-1]

        data = {
            "timestamp": str(self.get_clock().now().nanoseconds),
            "robot": self.robot_name,
            "task_index": self.current_task_index,
            "stage": self.stage,
            "next_waypoint": {
                "x": goal.x,
                "y": goal.y
            }
        }

        msg = String()
        msg.data = json.dumps(data)

        self.next_waypoint_pub.publish(msg)

    # Reports the robot's current operational state
    def publish_robot_state(self, state_name):
        data = {
            "timestamp": str(self.get_clock().now().nanoseconds),
            "robot": self.robot_name,
            "state": state_name,
            "task_index": self.current_task_index,
            "stage": self.stage
        }

        msg = String()
        msg.data = json.dumps(data)

        self.robot_state_pub.publish(msg)

    # Publishes the complete path currently being executed
    def publish_planned_path(self):
        data = {
            "timestamp": str(self.get_clock().now().nanoseconds),
            "robot": self.robot_name,
            "task_index": self.current_task_index,
            "stage": self.stage,
            "num_waypoints": len(self.path),
            "path": []
        }

        for idx, wp in enumerate(self.path):

            data["path"].append({
                "index": idx,
                "x": wp.x,
                "y": wp.y,
            })

        msg = String()
        msg.data = json.dumps(data)

        self.planned_path_pub.publish(msg)

# ------------------------------------------------------------------
# ROS 2 node entry point.
#
# Initializes the middleware, creates the controller instance, and
# hands execution over to the ROS event loop.
# ------------------------------------------------------------------

def main():
    rclpy.init()
    controller = Controller()
    rclpy.spin(controller)

if __name__ == "__main__":
    main()