# ------------------------------------------------------------------
# RHCR PATH ANIMATION AND VISUALIZATION TOOL
#
# This script visualizes RHCR-generated agent trajectories on a
# grid map through an animated simulation.
#
# Supported features:
# - RHCR map (.grid) loading
# - Agent path parsing
# - Goal visualization
# - Dynamic obstacle updates
# - Collision highlighting
# - Interactive playback
#
# The animation reconstructs agent movement over time,
# displaying both static map information and dynamic events
# such as pickups, deliveries, and obstacle state changes.
#
# The tool also computes and stores the resulting makespan
# for later performance analysis.
# ------------------------------------------------------------------

import argparse
import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib import animation
from matplotlib.patches import Circle, Rectangle

COLORS = [
    "orange",
    "tab:blue",
    "tab:green",
    "tab:orange",
    "tab:red",
    "tab:purple",
    "tab:brown",
    "tab:pink",
    "tab:gray",
    "tab:olive",
    "tab:cyan",
]

# --------------------------------------------------------------
# Instance directory resolution
#
# Locates the directory associated with a benchmark instance.
#
# Search order:
# 1. solver/instances/<boxes_dir>/example<number>
# 2. solver/instances/example<number> (legacy layout)
#
# Returns the first matching directory.
# --------------------------------------------------------------

def resolve_example_dir(project_root: Path, number: str, boxes_dir: str) -> Path:
    base = project_root / "solver" / "instances"
    with_boxes = base / boxes_dir / f"example{number}"
    legacy = base / f"example{number}"
    if with_boxes.exists():
        return with_boxes
    if legacy.exists():
        return legacy
    return with_boxes

# --------------------------------------------------------------
# RHCR path file resolver
#
# Attempts to locate RHCR output files generated by different
# execution configurations.
#
# Supported layouts:
# - exampleX_rhcr_paths.txt
# - exampleX_rhcr_paths/
# - Nested rhcr_paths.txt outputs
#
# Returns the first valid candidate found.
# --------------------------------------------------------------

def resolve_default_rhcr_path(example_dir: Path, num_example: str) -> Path:
    name = f"example{num_example}"
    candidates = [
        example_dir / f"{name}_rhcr_paths.txt" / "rhcr_paths.txt",
        example_dir / f"{name}_rhcr_paths" / "rhcr_paths.txt",
        example_dir / f"{name}_rhcr_paths.txt",
        example_dir / f"{name}_rhcr_paths",
    ]
    for c in candidates:
        if c.exists():
            return c
    return candidates[0]

# --------------------------------------------------------------
# Shortcut argument expansion
#
# Automatically derives map and path file locations from the
# selected benchmark instance.
#
# This allows the user to specify only:
# - Example number
# - Box configuration
#
# Instead of manually providing all file paths.
# --------------------------------------------------------------

def apply_shortcut_mode(args):
    if args.num_example is None:
        return

    boxes_dir = args.boxes_dir or f"{args.num_boxes}_boxes"
    project_root = Path(__file__).resolve().parents[1]
    example_dir = resolve_example_dir(project_root, args.num_example, boxes_dir)
    name = f"example{args.num_example}"

    if args.map is None:
        args.map = str(example_dir / f"{name}_map.grid")
    if args.paths is None:
        args.paths = str(resolve_default_rhcr_path(example_dir, args.num_example))

# --------------------------------------------------------------
# RHCR map loader
#
# Reads a RHCR .grid file and reconstructs:
# - Grid dimensions
# - Obstacle locations
#
# The file is interpreted as a node-based map where each
# record describes a cell and its traversal properties.
#
# Returns:
# - Number of rows
# - Number of columns
# - Boolean obstacle matrix
# --------------------------------------------------------------

def load_grid_map(map_file: Path):
    lines = [ln.strip() for ln in map_file.read_text().splitlines() if ln.strip()]
    if len(lines) < 4 or not lines[0].lower().startswith("grid size"):
        raise ValueError(f"Unsupported map format: {map_file}")

    rows, cols = [int(x) for x in lines[1].split(",")]
    header = lines[2].split(",")
    header_idx = {k: i for i, k in enumerate(header)}
    cells = [ln.split(",") for ln in lines[3:]]
    if len(cells) != rows * cols:
        raise ValueError(f"Map cell count mismatch in {map_file}")

    obstacles = np.zeros((rows, cols), dtype=bool)
    for tokens in cells:
        idx = int(tokens[header_idx["id"]])
        cell_type = tokens[header_idx["type"]]
        x = int(tokens[header_idx["x"]])
        y = int(tokens[header_idx["y"]])
        # The RHCR map uses x=col and y=row.
        if idx != y * cols + x:
            # Keep going, but still rely on x/y coordinates.
            pass
        if cell_type == "Obstacle":
            obstacles[y, x] = True
    return rows, cols, obstacles

# --------------------------------------------------------------
# Agent state interpolation
#
# Computes the agent position at an arbitrary simulation time.
#
# If the requested timestamp lies between two recorded states,
# linear interpolation is applied to generate smooth movement
# during animation playback.
#
# Returns:
# - Interpolated position
# - Final known position if simulation time exceeds path
# --------------------------------------------------------------

def _state_at_t(path, t):
    if not path:
        return None
    if t <= path[0][0]:
        return path[0][1]
    for i in range(1, len(path)):
        t0, p0 = path[i - 1]
        t1, p1 = path[i]
        if t <= t1:
            if t1 == t0:
                return p1
            a = (t - t0) / (t1 - t0)
            return (p0[0] + a * (p1[0] - p0[0]), p0[1] + a * (p1[1] - p0[1]))
    return path[-1][1]

# --------------------------------------------------------------
# Assigned-goal path parser
#
# Reads RHCR path files containing:
# - Agent trajectories
# - Goal assignments
# - Goal completion timestamps
#
# Extracted information:
# - Agent paths
# - Assigned goals
# - Goal reach times
# - Overall simulation horizon
#
# These data are later used to animate deliveries and dynamic
# obstacle state transitions.
# --------------------------------------------------------------

def parse_assigned_goal_paths(path_file: Path):
    lines = [ln.strip() for ln in path_file.read_text().splitlines() if ln.strip()]
    if not lines:
        raise ValueError(f"Empty path file: {path_file}")

    # First non-comment line can be number of agents.
    start = 0
    if re.fullmatch(r"\d+", lines[0]):
        start = 1

    agents = {}
    goals = {}
    reached_times = {}
    max_t = 0
    loc_re = re.compile(r"(\d+)\[(\d+),(\d+)\]@(\d+)")
    for ln in lines[start:]:
        if ln.startswith("#"):
            continue
        if ",path=" not in ln:
            continue
        prefix, path_part = ln.split(",path=", 1)
        m = re.match(r"agent\s+(\d+),", prefix)
        if not m:
            continue
        agent = int(m.group(1))

        # goals are the third CSV field in prefix: agent,start,goals,...
        prefix_tokens = prefix.split(",")
        if len(prefix_tokens) >= 3:
            goal_str = prefix_tokens[2]
            gvals = [int(x) for x in goal_str.split("|") if x]
            goals[agent] = gvals
        else:
            goals[agent] = []
        if len(prefix_tokens) >= 5:
            t_str = prefix_tokens[4]
            tvals = [int(x) for x in t_str.split("|") if x]
            reached_times[agent] = tvals
        else:
            reached_times[agent] = []

        entries = []
        for m2 in loc_re.finditer(path_part):
            _loc = int(m2.group(1))
            row = int(m2.group(2))
            col = int(m2.group(3))
            tt = int(m2.group(4))
            entries.append((tt, (col, row)))
            max_t = max(max_t, tt)
        entries.sort(key=lambda x: x[0])
        agents[agent] = entries
    return agents, goals, reached_times, max_t

# --------------------------------------------------------------
# Basic path parser
#
# Reads simplified RHCR path files containing only:
# - Location identifiers
# - Timesteps
#
# Node identifiers are converted back into grid coordinates
# using the map dimensions.
#
# Returns:
# - Agent trajectories
# - Empty goal assignments
# - Simulation horizon
# --------------------------------------------------------------

def parse_basic_paths(path_file: Path, cols: int):
    lines = [ln.strip() for ln in path_file.read_text().splitlines() if ln.strip()]
    if not lines:
        raise ValueError(f"Empty path file: {path_file}")
    idx = 0
    if re.fullmatch(r"\d+", lines[0]):
        idx = 1
    agents = {}
    max_t = 0
    for agent_id, ln in enumerate(lines[idx:]):
        entries = []
        for token in ln.split(";"):
            token = token.strip()
            if not token:
                continue
            parts = token.split(",")
            if len(parts) < 3:
                continue
            loc = int(parts[0])
            t = int(parts[2])
            row = loc // cols
            col = loc % cols
            entries.append((t, (col, row)))
            max_t = max(max_t, t)
        entries.sort(key=lambda x: x[0])
        agents[agent_id] = entries
    goals = {a: [] for a in agents}
    return agents, goals, max_t

# --------------------------------------------------------------
# RHCR animation class
#
# Responsible for rendering and updating the simulation.
#
# Visualized elements:
# - Static obstacles
# - Dynamic delivery boxes
# - Agent goals
# - Agent positions
# - Collision events
#
# Agent motion is interpolated between recorded states to
# produce smooth animations.
#
# Dynamic obstacle updates reflect pickup and delivery actions
# performed during execution.
# --------------------------------------------------------------

class RHCRAnimation:
    # Figure and plotting configuration
    def __init__(self, rows, cols, obstacles, agent_paths, agent_goals, t_max, speed=10, obstacle_toggle_events=None):
        self.rows = rows
        self.cols = cols
        self.obstacles = obstacles
        self.agent_paths = agent_paths
        self.agent_goals = agent_goals
        self.t_max = t_max
        self.speed = speed
        self.obstacle_toggle_events = sorted(obstacle_toggle_events or [], key=lambda x: x[0])

        aspect = cols / max(rows, 1)
        self.fig = plt.figure(frameon=False, figsize=(6 * aspect, 6))
        self.ax = self.fig.add_subplot(111, aspect="equal")
        self.fig.subplots_adjust(left=0, right=1, bottom=0, top=1)
        self.ax.set_xlim(-0.5, cols - 0.5)
        self.ax.set_ylim(-0.5, rows - 0.5)
        self.ax.set_xticks([])
        self.ax.set_yticks([])

        self.patches = []
        self.artists = []
        self.circles = {}
        self.labels = {}
        self.obstacle_patches = {}
        self.dynamic_box_patches = {}
        self.pickup_goal_patches = {}
        self.pickup_event_time = {}
        for ev_t, ev_loc, is_open in self.obstacle_toggle_events:
            if is_open and ev_loc not in self.pickup_event_time:
                self.pickup_event_time[ev_loc] = ev_t

        # Boundary
        self.patches.append(
            Rectangle((-0.5, -0.5), cols, rows, facecolor="none", edgecolor="black", linewidth=1)
        )
        
        # Static obstacle rendering
        for r in range(rows):
            for c in range(cols):
                if obstacles[r, c]:
                    patch = Rectangle((c - 0.5, (rows - 1 - r) - 0.5), 1, 1, facecolor="gray", edgecolor="gray")
                    self.patches.append(patch)
                    self.obstacle_patches[(r, c)] = patch
        
        # ----------------------------------------------------------
        # Dynamic obstacle overlays
        #
        # Used to visualize box delivery locations that become
        # blocked or unblocked during execution.
        # ----------------------------------------------------------

        event_locs = {loc for _, loc, _ in self.obstacle_toggle_events}
        for rr, cc in event_locs:
            if 0 <= rr < rows and 0 <= cc < cols and not obstacles[rr, cc]:
                patch = Rectangle((cc - 0.5, (rows - 1 - rr) - 0.5), 1, 1,
                                  facecolor="gray", edgecolor="black", alpha=0.9, visible=False)
                self.dynamic_box_patches[(rr, cc)] = patch
                self.patches.append(patch)

        # ----------------------------------------------------------
        # Goal visualization
        #
        # Goals are represented as colored squares matching the
        # responsible agent.
        # ----------------------------------------------------------

        for a, glist in agent_goals.items():
            color = COLORS[a % len(COLORS)]
            for goal in glist:
                gr = goal // cols
                gc = goal % cols
                patch = Rectangle((gc - 0.25, (rows - 1 - gr) - 0.25), 0.5, 0.5,
                                  facecolor=color, edgecolor="black", alpha=0.45)
                self.patches.append(patch)
                self.pickup_goal_patches.setdefault((gr, gc), []).append((patch, color))

        # ----------------------------------------------------------
        # Agent initialization
        #
        # Creates graphical representations and labels for every
        # agent participating in the simulation.
        # ----------------------------------------------------------
        
        for a in sorted(agent_paths.keys()):
            path = agent_paths[a]
            if not path:
                continue
            color = COLORS[a % len(COLORS)]
            x0, y0 = path[0][1]
            y0 = rows - 1 - y0
            c = Circle((x0, y0), 0.30, facecolor=color, edgecolor="black")
            c.original_face_color = color
            self.circles[a] = c
            self.patches.append(c)
            txt = self.ax.text(x0, y0 + 0.35, str(a), ha="center", va="center", fontsize=9)
            self.labels[a] = txt
            self.artists.append(txt)

        # ----------------------------------------------------------
        # Animation controller
        #
        # Updates the visualization at a fixed frame rate.
        # ----------------------------------------------------------

        self.anim = animation.FuncAnimation(
            self.fig,
            self._animate,
            init_func=self._init,
            frames=int(self.t_max * self.speed) + 1,
            interval=1000 / self.speed,
            blit=True,
        )

    # ----------------------------------------------------------
    # Initial rendering callback
    #
    # Registers all visual elements with the plotting canvas.
    # ----------------------------------------------------------

    def _init(self):
        for p in self.patches:
            self.ax.add_patch(p)
        for a in self.artists:
            self.ax.add_artist(a)
        return self.patches + self.artists

    # ----------------------------------------------------------
    # Frame update callback
    #
    # Updates:
    # - Dynamic obstacles
    # - Goal states
    # - Agent positions
    # - Collision indicators
    #
    # Executed once per animation frame.
    # ----------------------------------------------------------

    def _animate(self, frame):
        t = frame / self.speed

        # Dynamic obstacles: pickup opens a box-cell, drop closes it again
        open_cells = set()
        closed_cells = set()

        for ev_t, ev_loc, is_open in self.obstacle_toggle_events:
            if ev_t <= t:
                if is_open:
                    open_cells.add(ev_loc)
                    closed_cells.discard(ev_loc)
                else:
                    open_cells.discard(ev_loc)
                    closed_cells.add(ev_loc)
        for (r, c), patch in self.obstacle_patches.items():
            if (r, c) in open_cells:
                patch.set_facecolor("none")
                patch.set_edgecolor("none")
            else:
                patch.set_facecolor("gray")
                patch.set_edgecolor("gray")
        for loc, patch in self.dynamic_box_patches.items():
            patch.set_visible(loc in closed_cells)
        for loc, patch_list in self.pickup_goal_patches.items():
            picked = t >= self.pickup_event_time.get(loc, float("inf"))
            for patch, color in patch_list:
                if picked:
                    patch.set_facecolor("none")
                    patch.set_edgecolor(color)
                    patch.set_linestyle(":")
                    patch.set_linewidth(2.0)
                    patch.set_alpha(1.0)
                else:
                    patch.set_facecolor(color)
                    patch.set_edgecolor("black")
                    patch.set_linestyle("-")
                    patch.set_linewidth(1.0)
                    patch.set_alpha(0.45)

        for a, path in self.agent_paths.items():
            pos = _state_at_t(path, t)
            if pos is None:
                continue
            x, y = pos
            y = self.rows - 1 - y
            self.circles[a].center = (x, y)
            self.labels[a].set_position((x, y + 0.35))

        for c in self.circles.values():
            c.set_facecolor(c.original_face_color)

        # ----------------------------------------------------------
        # Collision highlighting
        #
        # Agents whose visual representations overlap are marked
        # in red to indicate a potential collision event.
        # ----------------------------------------------------------
        
        ids = sorted(self.circles.keys())
        for i in range(len(ids)):
            for j in range(i + 1, len(ids)):
                a1 = ids[i]
                a2 = ids[j]
                p1 = np.array(self.circles[a1].center)
                p2 = np.array(self.circles[a2].center)
                if np.linalg.norm(p1 - p2) < 0.6:
                    self.circles[a1].set_facecolor("red")
                    self.circles[a2].set_facecolor("red")
        return self.patches + self.artists

    # ----------------------------------------------------------
    # Animation exporter
    #
    # Saves the animation to a video or GIF file.
    # ----------------------------------------------------------

    def save(self, out_file: Path, fps: int = 20):
        self.anim.save(str(out_file), fps=fps, dpi=160)

    # ----------------------------------------------------------
    # Interactive viewer
    #
    # Opens the animation window for real-time inspection.
    # ----------------------------------------------------------

    def show(self):
        plt.show()

# --------------------------------------------------------------
# Main visualization pipeline
#
# Workflow:
# 1. Parse CLI arguments
# 2. Resolve benchmark files
# 3. Load RHCR map
# 4. Load agent trajectories
# 5. Generate dynamic obstacle events
# 6. Create animation
# 7. Compute makespan
# 8. Save makespan statistics
# 9. Display or export animation
# --------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Animate RHCR paths on a .grid map.")
    parser.add_argument("num_example", nargs="?", help="Example number (ex: 1 for example1)")
    parser.add_argument(
        "num_boxes",
        nargs="?",
        type=int,
        default=9,
        help="Number of boxes (defines the folder <num boxes>boxes by default)",
    )
    parser.add_argument("--boxes-dir", type=str, default=None,
                        help="Folder inside solver/instances (ex.: 8_boxes, 10_boxes)")
    parser.add_argument("--map", default=None, help="Path to RHCR .grid file")
    parser.add_argument("--paths", default=None, help="Path to RHCR assigned_goal_paths*.txt or paths.txt")
    parser.add_argument("--speed", type=int, default=10, help="Frames per timestep")
    parser.add_argument("--save", default="", help="Optional output video/gif path instead of interactive show")
    parser.add_argument("--not-show", action="store_true", help="Do not show the animation")
    args = parser.parse_args()
    apply_shortcut_mode(args)

    if args.map is None or args.paths is None:
        parser.error(
            "Provide positional args <num_example> <num_boxes> or both --map and --paths."
        )

    map_file = Path(args.map)
    path_file = Path(args.paths)
    rows, cols, obstacles = load_grid_map(map_file)

    first = path_file.read_text().splitlines()[0].strip() if path_file.exists() else ""
    obstacle_toggle_events = []
    if "agent " in path_file.read_text() or "path=" in path_file.read_text():
        agent_paths, goals, reached_times, t_max = parse_assigned_goal_paths(path_file)

        # Build dynamic obstacle events from reached goals:
        # odd reached index (1st,3rd,...) -> pickup -> open obstacle
        # even reached index (2nd,4th,...) -> drop -> close obstacle
        for a, glist in goals.items():
            tlist = reached_times.get(a, [])
            for i, g in enumerate(glist):
                if i >= len(tlist):
                    break
                tt = tlist[i]
                if tt < 0:
                    continue
                gr = g // cols
                gc = g % cols
                if 0 <= gr < rows and 0 <= gc < cols:
                    is_open = ((i + 1) % 2 == 1)
                    obstacle_toggle_events.append((tt, (gr, gc), is_open))
    else:
        agent_paths, goals, t_max = parse_basic_paths(path_file, cols)
        reached_times = {}

    anim = RHCRAnimation(
        rows, cols, obstacles, agent_paths, goals, t_max, speed=args.speed,
        obstacle_toggle_events=obstacle_toggle_events
    )

    # Add 5 more seconds to the makespan because the last robot does not
    # take this into account

    makespan = anim.t_max + 5
    print(f"Makespan: {makespan:.5f} s")

    project_root = Path(__file__).resolve().parents[1]
    boxes_dir = args.boxes_dir or f"{args.num_boxes}_boxes"
    example_dir = project_root / "solver" / "instances" / boxes_dir / f"example{args.num_example}"

    output_file = example_dir / "RHCR_makespan.txt"

    output_file.parent.mkdir(parents=True, exist_ok=True)

    with open(output_file, "w") as f:
        f.write(f"{makespan:.5f}\n")

    if args.save:
        anim.save(Path(args.save))

    if args.not_show:
        print("")
    else:
        anim.show()
        print("")

if __name__ == "__main__":
    main()